@@include('../components/header/header.js');
@@include('../components/main/main_slider/main_slider.js');
@@include('../components/main/main_news/main_news.js');
@@include('../components/main/main_team/main_team.js');
@@include('../components/patents/patents_bottom/patents_bottom.js');
@@include('../components/team/team_slider/team_slider.js');
@@include('../components/news/news.js');
@@include('../components/products/products.js');
@@include('../components/contacts/contacts_map/contacts_map.js');
